### ISSUE TITLE
Invalid/unknown timezone crashes the WhoisOnline widget in the dashboard

### ISSUE THREAD

**Issue by OptimusCrime** [modxcms/revolution#13727]
### Summary

The code for the WhoIsOnline widget tries to create a new instance of `DateTime` by supplying a timezone. If either the system setting `date_timezone` or the system is configured in a way that results in an unknown timezone for PHP, it will throw an exception. This exception is never caught and results in a fatal 500 error.

We should wrap the construction in a try/catch block, and fall back to creating a `DateTime` instance without supplying any timezone if that does not work.

Relevant code: [manager/controllers/default/dashboard/widget.grid-online.php#L14-L17](https://github.com/modxcms/revolution/blob/10692efe83cdd6a33571e16756c243a7ab2aadbd/manager/controllers/default/dashboard/widget.grid-online.php#L14-L17).

Stacktrace:

```
Fatal error: Uncaught Exception: DateTime::__construct(): Failed to parse time string (CST6CDT) at position 3 (6): Unexpected character in /home/xxxx/public_html/manager/controllers/default/dashboard/widget.grid-online.php:17 Stack trace: #0 /home/xxxx/public_html/manager/controllers/default/dashboard/widget.grid-online.php(17): DateTime->__construct('CST6CDT') #1 /home/xxxx/core/model/modx/moddashboardwidget.class.php(246): modDashboardWidgetWhoIsOnline->render() #2 /home/xxxx/core/model/modx/moddashboardwidget.class.php(118): modDashboardWidgetInterface->process() #3 /home/xxxx/core/model/modx/moddashboard.class.php(78): modDashboardWidget->getContent(Object(WelcomeManagerController)) #4 /home/xxxx/public_html/manager/controllers/default/welcome.class.php(64): modDashboard->render(Object(WelcomeManagerController)) #5 /home/xxxx/core/model/modx/modmanagercontroller.class.php(149): WelcomeManagerController->process(Array) #6 /home/xxxx/core/model/modx/modmanagerresponse.class.php(74): modMa in /home/xxxx/public_html/manager/controllers/default/dashboard/widget.grid-online.php on line 17
```

### Observed behavior
The code throws an fatal 500 error that it is unable to recover from.

### Expected behavior
Should either fall back to no timezone or crash "gracefully".

### Environment
MODX 2.6.0-pl. Any browser.

**Comment by gdubois414** [comment]
This occurred for me when upgrading to 2.6.1-pl. I discovered that the date_timezone field in the modx_system_settings database table was empty.

The fix for me was to manually update the field in phpmyadmin to a recognized timezone.

**Comment by Elawphant** [comment]
The solution proposed by gdubois414 worked for me, but only with value 4095 (ALL_WITH_BC).

**Comment by Ibochkarev** [comment]
### Triage (current 3.x)

**Still valid on 3.x.** The crash path moved out of the dashboard widget file into the processor the widget calls. Reproduced the original `CST6CDT` failure against current `GetOnline` code on PHP 8.4.

### Current behavior

- Widget: `manager/controllers/default/dashboard/widget.grid-online.php` only runs `GetOnline` and renders `onlineusers.tpl`. No local `DateTime` there anymore.
- Processor: `core/src/Revolution/Processors/Security/User/GetOnline.php` → `prepareQueryBeforeCount()`:

```php
$date_timezone = !empty($this->modx->getOption('date_timezone'))
    ? $this->modx->getOption('date_timezone')
    : date_default_timezone_get();
$datetime = new DateTime($date_timezone);
```

- First argument of `DateTime` is a **datetime string**, not a timezone id. With `date_timezone = CST6CDT` (value from the report), PHP throws the same parse error as in 2.6.
- Note: `CST6CDT` is a valid `DateTimeZone` on current PHP. `new DateTime('now', new DateTimeZone('CST6CDT'))` works. The bug is the wrong constructor usage, not “unknown timezone” alone.
- Softening vs 2.6: `modDashboardWidgetInterface::process()` catches `Throwable` and shows `error.tpl` for that widget. Welcome may not hard-500 the whole page, but Who’s Online still fails for the request.

### Why the widget dies

Cutoff “online in last 20 minutes” builds `now − PT20M` by stuffing the timezone name into `new DateTime($tz)`. Invalid-as-datetime (or odd) values explode before the query runs. No try/catch around that construction in `GetOnline`.

### Suggested fix

In `GetOnline::prepareQueryBeforeCount()`:

1. Resolve name from `date_timezone`, else `date_default_timezone_get()`.
2. `new DateTimeZone($name)` in try/catch; on failure fall back to default (or UTC) and optionally log a warning.
3. `new DateTime('now', $tz)` (or `DateTimeImmutable`), then subtract 20 minutes for `$timeToCheck`.
4. Keep using that cutoff in the existing `occurred` query.

### Related

- Original stack pointed at `widget.grid-online.php` (2.x). Logic now lives in `Processors\Security\User\GetOnline`.
- Widget-level try/catch only masks a full manager 500; it does not fix Who’s Online.

No linked fix PR for #13727. Minimal patch: correct `DateTime`/`DateTimeZone` usage + fallback when `date_timezone` is invalid.
