### ISSUE TITLE
Error saving default admin account

### ISSUE THREAD

**Issue by Ibochkarev** [modxcms/revolution#14765]
### Summary
Error saving default admin account. `Array ( [0] => 00000 [1] => [2] => )`

### Step to reproduce
Install the night assembly

### Observed behavior
After entering the administrator data, click on the Next button, we get to the Test screen, I get an error: Error saving default admin account. `Array ( [0] => 00000 [1] => [2] => )`

I click further I receive an error:
```
Fatal error: Uncaught Error: Call to a member function get() on null in C:\laragon\www\core\src\Revolution\Processors\Security\Login.php:173 Stack trace: #0 C:\laragon\www\core\src\Revolution\Processors\Security\Login.php(249): MODX\Revolution\Processors\Security\Login->checkIsBlocked() #1 C:\laragon\www\core\src\Revolution\Processors\Security\Login.php(430): MODX\Revolution\Processors\Security\Login->beforeLogin() #2 C:\laragon\www\core\src\Revolution\modProcessor.php(178): MODX\Revolution\Processors\Security\Login->process() #3 C:\laragon\www\core\src\Revolution\modX.php(1721): MODX\Revolution\modProcessor->run() #4 C:\laragon\www\manager\controllers\default\security\login.class.php(448): MODX\Revolution\modX->runProcessor('MODX\\Revolution...', Array) #5 C:\laragon\www\manager\controllers\default\security\login.class.php(391): SecurityLoginManagerController->handleLogin() #6 C:\laragon\www\manager\controllers\default\security\login.class.php(60): SecurityLoginManagerController->handlePost() #7 C:\laragon\www\core\src\R in C:\laragon\www\core\src\Revolution\Processors\Security\Login.php on line 173
```
In the error_log file, the following
```
[18-Sep-2019 17:13:12 UTC] PHP Fatal error:  Uncaught Error: Call to a member function get() on null in C:\laragon\www\core\src\Revolution\Processors\Security\Login.php:173
Stack trace:
#0 C:\laragon\www\core\src\Revolution\Processors\Security\Login.php(249): MODX\Revolution\Processors\Security\Login->checkIsBlocked()
#1 C:\laragon\www\core\src\Revolution\Processors\Security\Login.php(430): MODX\Revolution\Processors\Security\Login->beforeLogin()
#2 C:\laragon\www\core\src\Revolution\modProcessor.php(178): MODX\Revolution\Processors\Security\Login->process()
#3 C:\laragon\www\core\src\Revolution\modX.php(1721): MODX\Revolution\modProcessor->run()
#4 C:\laragon\www\manager\controllers\default\security\login.class.php(448): MODX\Revolution\modX->runProcessor('MODX\\Revolution...', Array)
#5 C:\laragon\www\manager\controllers\default\security\login.class.php(391): SecurityLoginManagerController->handleLogin()
#6 C:\laragon\www\manager\controllers\default\security\login.class.php(60): SecurityLoginManagerController->handlePost()
#7 C:\laragon\www\core\src\R in C:\laragon\www\core\src\Revolution\Processors\Security\Login.php on line 173
[18-Sep-2019 17:13:21 UTC] PHP Fatal error:  Uncaught Error: Call to a member function get() on null in C:\laragon\www\core\src\Revolution\Processors\Security\Login.php:173
Stack trace:
#0 C:\laragon\www\core\src\Revolution\Processors\Security\Login.php(249): MODX\Revolution\Processors\Security\Login->checkIsBlocked()
#1 C:\laragon\www\core\src\Revolution\Processors\Security\Login.php(430): MODX\Revolution\Processors\Security\Login->beforeLogin()
#2 C:\laragon\www\core\src\Revolution\modProcessor.php(178): MODX\Revolution\Processors\Security\Login->process()
#3 C:\laragon\www\core\src\Revolution\modX.php(1721): MODX\Revolution\modProcessor->run()
#4 C:\laragon\www\manager\controllers\default\security\login.class.php(448): MODX\Revolution\modX->runProcessor('MODX\\Revolution...', Array)
#5 C:\laragon\www\manager\controllers\default\security\login.class.php(391): SecurityLoginManagerController->handleLogin()
#6 C:\laragon\www\manager\controllers\default\security\login.class.php(60): SecurityLoginManagerController->handlePost()
#7 C:\laragon\www\core\src\R in C:\laragon\www\core\src\Revolution\Processors\Security\Login.php on line 173
[18-Sep-2019 17:13:26 UTC] PHP Fatal error:  Uncaught Error: Call to a member function get() on null in C:\laragon\www\core\src\Revolution\Processors\Security\Login.php:173
Stack trace:
#0 C:\laragon\www\core\src\Revolution\Processors\Security\Login.php(249): MODX\Revolution\Processors\Security\Login->checkIsBlocked()
#1 C:\laragon\www\core\src\Revolution\Processors\Security\Login.php(430): MODX\Revolution\Processors\Security\Login->beforeLogin()
#2 C:\laragon\www\core\src\Revolution\modProcessor.php(178): MODX\Revolution\Processors\Security\Login->process()
#3 C:\laragon\www\core\src\Revolution\modX.php(1721): MODX\Revolution\modProcessor->run()
#4 C:\laragon\www\manager\controllers\default\security\login.class.php(448): MODX\Revolution\modX->runProcessor('MODX\\Revolution...', Array)
#5 C:\laragon\www\manager\controllers\default\security\login.class.php(391): SecurityLoginManagerController->handleLogin()
#6 C:\laragon\www\manager\controllers\default\security\login.class.php(60): SecurityLoginManagerController->handlePost()
#7 C:\laragon\www\core\src\R in C:\laragon\www\core\src\Revolution\Processors\Security\Login.php on line 173
[18-Sep-2019 17:17:10 UTC] PHP Fatal error:  Uncaught Error: Call to a member function get() on null in C:\laragon\www\core\src\Revolution\Processors\Security\Login.php:173
Stack trace:
#0 C:\laragon\www\core\src\Revolution\Processors\Security\Login.php(249): MODX\Revolution\Processors\Security\Login->checkIsBlocked()
#1 C:\laragon\www\core\src\Revolution\Processors\Security\Login.php(430): MODX\Revolution\Processors\Security\Login->beforeLogin()
#2 C:\laragon\www\core\src\Revolution\modProcessor.php(178): MODX\Revolution\Processors\Security\Login->process()
#3 C:\laragon\www\core\src\Revolution\modX.php(1721): MODX\Revolution\modProcessor->run()
#4 C:\laragon\www\manager\controllers\default\security\login.class.php(448): MODX\Revolution\modX->runProcessor('MODX\\Revolution...', Array)
#5 C:\laragon\www\manager\controllers\default\security\login.class.php(391): SecurityLoginManagerController->handleLogin()
#6 C:\laragon\www\manager\controllers\default\security\login.class.php(60): SecurityLoginManagerController->handlePost()
#7 C:\laragon\www\core\src\R in C:\laragon\www\core\src\Revolution\Processors\Security\Login.php on line 173
[26-Sep-2019 12:16:53 UTC] PHP Fatal error:  Uncaught Error: Call to a member function get() on null in C:\laragon\www\core\src\Revolution\Processors\Security\Login.php:173
Stack trace:
#0 C:\laragon\www\core\src\Revolution\Processors\Security\Login.php(249): MODX\Revolution\Processors\Security\Login->checkIsBlocked()
#1 C:\laragon\www\core\src\Revolution\Processors\Security\Login.php(430): MODX\Revolution\Processors\Security\Login->beforeLogin()
#2 C:\laragon\www\core\src\Revolution\modProcessor.php(178): MODX\Revolution\Processors\Security\Login->process()
#3 C:\laragon\www\core\src\Revolution\modX.php(1721): MODX\Revolution\modProcessor->run()
#4 C:\laragon\www\manager\controllers\default\security\login.class.php(448): MODX\Revolution\modX->runProcessor('MODX\\Revolution...', Array)
#5 C:\laragon\www\manager\controllers\default\security\login.class.php(391): SecurityLoginManagerController->handleLogin()
#6 C:\laragon\www\manager\controllers\default\security\login.class.php(60): SecurityLoginManagerController->handlePost()
#7 C:\laragon\www\core\src\R in C:\laragon\www\core\src\Revolution\Processors\Security\Login.php on line 173
```

### Environment
MODX Revolution 3.0.0-dev Built on Sep 24, 2019, apache 2.4.35 and version, mysql 5.7.24, php 7.2.19 browser

**Comment by Mark-H** [comment]
That fatal error suggests the modUserProfile wasn't created/can't be loaded... but doesn't say why. Could be a mysql strict error or something, but there's not really enough info in this issue alone to identify what that is.

**Comment by Ibochkarev** [comment]
@Mark-H What else can be provided?

**Comment by Mark-H** [comment]
A mysql error message would be ideal, but from what you posted it may not be as easy to get that. Can you check if the user profile was created in the `modx_user_attributes` table?

Also can you please check the installation log (in core/cache/logs) to see if that may have some more information?

**Comment by Ibochkarev** [comment]
Log file in core/cache/logs

[install.config.2019-09-26T12.12.12.log](https://github.com/modxcms/revolution/files/3657805/install.config.2019-09-26T12.12.12.log)


![image](https://user-images.githubusercontent.com/2138260/65689956-da5d3f00-e08f-11e9-8fa1-18ac7167c03b.png)

**Comment by Ibochkarev** [comment]
![image](https://user-images.githubusercontent.com/2138260/65689845-ac77fa80-e08f-11e9-819c-e6bea78d1824.png)

**Comment by Mark-H** [comment]
Relevant error:

```
[2019-09-26 12:12:14] (ERROR @ C:\laragon\www\core\src\Revolution\modUserProfile.php : 57) Error HY000 executing statement:
INSERT INTO `modx_user_attributes` (`internalKey`, `fullname`, `email`, `phone`, `mobilephone`, `blocked`, `blockeduntil`, `blockedafter`, `logincount`, `lastlogin`, `thislogin`, `failedlogincount`, `sessionid`, `dob`, `gender`, `address`, `country`, `city`, `state`, `zip`, `fax`, `photo`, `comment`, `website`) VALUES (1, 'Администратор по умолчанию', 'ivanx86@gmail.com', '', '', 0, 0, 0, 0, 0, 0, 0, '', 0, 0, '', '', '', '', '', '', '', '', '')
Array
(
    [0] => HY000
    [1] => 1366
    [2] => Incorrect string value: '\xD0\x90\xD0\xB4\xD0\xBC...' for column 'fullname' at row 1
)
```

Looks like the database/table wasn't created as UTF8.
