### ISSUE TITLE
PHP Fatal error:  Uncaught Error: Call to a member function fromArray()

### ISSUE THREAD

**Issue by Ibochkarev** [modxcms/revolution#15432]
### Summary
When I try to install modx 3 using composer, I get an error and the installation ends

### Step to reproduce

Try to install modx 3 using
`composer create-project modx/revolution . 3.x-dev`

### Observed behavior

``` bash
s22270@h3:~/www$ composer create-project modx/revolution . 3.x-dev
Creating a "modx/revolution" project at "./"
Installing modx/revolution (3.x-dev 1dc912bd1513f61d09c460eed281828dbf5769af)
  - Syncing modx/revolution (3.x-dev 1dc912b) into cache
  - Installing modx/revolution (3.x-dev 1dc912b): Cloning 1dc912bd15 from cache
Created project in /home/s22270/www/.
Loading composer repositories with package information
Updating dependencies
Lock file operations: 60 installs, 0 updates, 0 removals
  - Locking aws/aws-sdk-php (3.173.21)
  - Locking doctrine/instantiator (1.0.5)
  - Locking erusev/parsedown (1.7.4)
  - Locking guzzlehttp/guzzle (6.5.5)
  - Locking guzzlehttp/promises (1.4.0)
  - Locking guzzlehttp/psr7 (1.7.0)
  - Locking inlinestyle/inlinestyle (1.2.7)
  - Locking james-heinrich/phpthumb (v1.7.16)
  - Locking league/flysystem (1.0.70)
  - Locking league/flysystem-aws-s3-v3 (1.0.29)
  - Locking league/flysystem-cached-adapter (1.1.0)
  - Locking mtdowling/jmespath.php (2.6.0)
  - Locking myclabs/deep-copy (1.7.0)
  - Locking paragonie/random_compat (v9.99.100)
  - Locking phar-io/manifest (1.0.1)
  - Locking phar-io/version (1.0.1)
  - Locking phpdocumentor/reflection-common (1.0.1)
  - Locking phpdocumentor/reflection-docblock (4.3.4)
  - Locking phpdocumentor/type-resolver (0.5.1)
  - Locking phpmailer/phpmailer (v6.3.0)
  - Locking phpspec/prophecy (v1.10.3)
  - Locking phpunit/php-code-coverage (5.3.2)
  - Locking phpunit/php-file-iterator (1.4.5)
  - Locking phpunit/php-text-template (1.2.1)
  - Locking phpunit/php-timer (1.0.9)
  - Locking phpunit/php-token-stream (2.0.2)
  - Locking phpunit/phpunit (6.5.14)
  - Locking phpunit/phpunit-mock-objects (5.0.10)
  - Locking pimple/pimple (v3.2.3)
  - Locking psr/cache (1.0.1)
  - Locking psr/container (1.0.0)
  - Locking psr/http-message (1.0.1)
  - Locking psr/log (1.1.3)
  - Locking ralouphie/getallheaders (3.0.3)
  - Locking sebastian/code-unit-reverse-lookup (1.0.2)
  - Locking sebastian/comparator (2.1.3)
  - Locking sebastian/diff (2.0.1)
  - Locking sebastian/environment (3.1.0)
  - Locking sebastian/exporter (3.1.3)
  - Locking sebastian/global-state (2.0.0)
  - Locking sebastian/object-enumerator (3.0.4)
  - Locking sebastian/object-reflector (1.1.2)
  - Locking sebastian/recursion-context (3.0.1)
  - Locking sebastian/resource-operations (1.0.0)
  - Locking sebastian/version (2.0.1)
  - Locking simplepie/simplepie (1.5.6)
  - Locking smarty/smarty (v3.1.39)
  - Locking symfony/console (v3.4.47)
  - Locking symfony/css-selector (v3.4.47)
  - Locking symfony/debug (v3.4.47)
  - Locking symfony/polyfill-ctype (v1.19.0)
  - Locking symfony/polyfill-intl-idn (v1.19.0)
  - Locking symfony/polyfill-intl-normalizer (v1.19.0)
  - Locking symfony/polyfill-mbstring (v1.19.0)
  - Locking symfony/polyfill-php70 (v1.19.0)
  - Locking symfony/polyfill-php72 (v1.19.0)
  - Locking theseer/tokenizer (1.1.3)
  - Locking webmozart/assert (1.9.1)
  - Locking xpdo/xpdo (3.x-dev 6271aa9)
  - Locking yoast/phpunit-polyfills (0.2.0)
Writing lock file
Installing dependencies from lock file (including require-dev)
Package operations: 60 installs, 0 updates, 0 removals
  - Downloading aws/aws-sdk-php (3.173.21)
  - Syncing xpdo/xpdo (3.x-dev 6271aa9) into cache
  - Downloading yoast/phpunit-polyfills (0.2.0)
  - Installing erusev/parsedown (1.7.4): Extracting archive
  - Installing symfony/polyfill-php72 (v1.19.0): Extracting archive
  - Installing paragonie/random_compat (v9.99.100): Extracting archive
  - Installing symfony/polyfill-php70 (v1.19.0): Extracting archive
  - Installing symfony/polyfill-intl-normalizer (v1.19.0): Extracting archive
  - Installing symfony/polyfill-intl-idn (v1.19.0): Extracting archive
  - Installing ralouphie/getallheaders (3.0.3): Extracting archive
  - Installing psr/http-message (1.0.1): Extracting archive
  - Installing guzzlehttp/psr7 (1.7.0): Extracting archive
  - Installing guzzlehttp/promises (1.4.0): Extracting archive
  - Installing guzzlehttp/guzzle (6.5.5): Extracting archive
  - Installing symfony/css-selector (v3.4.47): Extracting archive
  - Installing inlinestyle/inlinestyle (1.2.7): Extracting archive
  - Installing james-heinrich/phpthumb (v1.7.16): Extracting archive
  - Installing league/flysystem (1.0.70): Extracting archive
  - Installing symfony/polyfill-mbstring (v1.19.0): Extracting archive
  - Installing mtdowling/jmespath.php (2.6.0): Extracting archive
  - Installing aws/aws-sdk-php (3.173.21): Extracting archive
  - Installing league/flysystem-aws-s3-v3 (1.0.29): Extracting archive
  - Installing psr/cache (1.0.1): Extracting archive
  - Installing league/flysystem-cached-adapter (1.1.0): Extracting archive
  - Installing myclabs/deep-copy (1.7.0): Extracting archive
  - Installing phar-io/version (1.0.1): Extracting archive
  - Installing phar-io/manifest (1.0.1): Extracting archive
  - Installing phpdocumentor/reflection-common (1.0.1): Extracting archive
  - Installing phpdocumentor/type-resolver (0.5.1): Extracting archive
  - Installing phpmailer/phpmailer (v6.3.0): Extracting archive
  - Installing sebastian/recursion-context (3.0.1): Extracting archive
  - Installing sebastian/exporter (3.1.3): Extracting archive
  - Installing sebastian/diff (2.0.1): Extracting archive
  - Installing sebastian/comparator (2.1.3): Extracting archive
  - Installing symfony/polyfill-ctype (v1.19.0): Extracting archive
  - Installing webmozart/assert (1.9.1): Extracting archive
  - Installing phpdocumentor/reflection-docblock (4.3.4): Extracting archive
  - Installing doctrine/instantiator (1.0.5): Extracting archive
  - Installing phpspec/prophecy (v1.10.3): Extracting archive
  - Installing theseer/tokenizer (1.1.3): Extracting archive
  - Installing sebastian/version (2.0.1): Extracting archive
  - Installing sebastian/environment (3.1.0): Extracting archive
  - Installing sebastian/code-unit-reverse-lookup (1.0.2): Extracting archive
  - Installing phpunit/php-token-stream (2.0.2): Extracting archive
  - Installing phpunit/php-text-template (1.2.1): Extracting archive
  - Installing phpunit/php-file-iterator (1.4.5): Extracting archive
  - Installing phpunit/php-code-coverage (5.3.2): Extracting archive
  - Installing phpunit/php-timer (1.0.9): Extracting archive
  - Installing phpunit/phpunit-mock-objects (5.0.10): Extracting archive
  - Installing psr/container (1.0.0): Extracting archive
  - Installing pimple/pimple (v3.2.3): Extracting archive
  - Installing sebastian/global-state (2.0.0): Extracting archive
  - Installing sebastian/object-reflector (1.1.2): Extracting archive
  - Installing sebastian/object-enumerator (3.0.4): Extracting archive
  - Installing sebastian/resource-operations (1.0.0): Extracting archive
  - Installing simplepie/simplepie (1.5.6): Extracting archive
  - Installing smarty/smarty (v3.1.39): Extracting archive
  - Installing psr/log (1.1.3): Extracting archive
  - Installing symfony/debug (v3.4.47): Extracting archive
  - Installing symfony/console (v3.4.47): Extracting archive
  - Installing xpdo/xpdo (3.x-dev 6271aa9): Cloning 6271aa9c9e from cache
  - Installing phpunit/phpunit (6.5.14): Extracting archive
  - Installing yoast/phpunit-polyfills (0.2.0): Extracting archive
26 package suggestions were added by new dependencies, use `composer suggest` to see details.
Package phpunit/php-token-stream is abandoned, you should avoid using it. No replacement was suggested.
Package phpunit/phpunit-mock-objects is abandoned, you should avoid using it. No replacement was suggested.
Generating autoload files
16 packages you are using are looking for funding.
Use the `composer fund` command to find out more!
Do you want to remove the existing VCS (.git, .svn..) history? [Y,n]? n
> @php -r "file_exists('_build/build.properties.php') || copy('_build/build.properties.sample.php', '_build/build.properties.php');"
> @php -r "file_exists('_build/build.config.php') || copy('_build/build.config.sample.php', '_build/build.config.php');"
> @php _build/transport.core.php
[2021-03-04 07:43:05] (INFO @ _build/transport.core.php) Beginning build script processes...
[2021-03-04 07:43:05] (INFO @ _build/transport.core.php) Removed pre-existing core/ and core.transport.zip.
[2021-03-04 07:43:05] (INFO @ _build/transport.core.php) Core transport package created.
[2021-03-04 07:43:05] (INFO @ _build/transport.core.php) Core Namespace packaged.
[2021-03-04 07:43:05] (INFO @ _build/transport.core.php) Default workspace packaged.
[2021-03-04 07:43:05] (INFO @ _build/transport.core.php) Packaged modx.com transport provider.
[2021-03-04 07:43:05] (INFO @ _build/transport.core.php) Packaged in 2 modMenus.
[2021-03-04 07:43:05] (INFO @ _build/transport.core.php) Packaged all default modContentTypes.
[2021-03-04 07:43:05] (INFO @ _build/transport.core.php) Packaged in 190 default events.
[2021-03-04 07:43:05] (ERROR @ /home/s22270/www/core/vendor/xpdo/xpdo/src/xPDO/xPDO.php : 806) Could not load class: modSystemSetting from mysql.odsystemsettin                                                                              g
PHP Fatal error:  Uncaught Error: Call to a member function fromArray() on null in /home/s22270/www/_build/data/transport.core.system_settings.php:1752
Stack trace:
#0 /home/s22270/www/_build/transport.core.php(242): include()
#1 {main}
  thrown in /home/s22270/www/_build/data/transport.core.system_settings.php on line 1752

Fatal error: Uncaught Error: Call to a member function fromArray() on null in /home/s22270/www/_build/data/transport.core.system_settings.php:1752
Stack trace:
#0 /home/s22270/www/_build/transport.core.php(242): include()
#1 {main}
  thrown in /home/s22270/www/_build/data/transport.core.system_settings.php on line 1752
Script @php _build/transport.core.php handling the post-create-project-cmd event returned with error code 255
```

**but the files are prepared for installation and it is possible to install using http: //your-path-to-modx.tld/setup**

At the last stage, you get an error

```shell
Failed to install MODX because MODX was unable to unpack the 
/home/s22270/www/core/packages/core.transport.zip package. Check that the file /home/s22270/www/core/packages/core.transport.zip exists, is writable, and can be written to the /home/s22270/www/core/packages/
```

### Related issue(s)/PR(s)
NA

### Environment
MODX 3 (git), php 7.4

**Comment by Mark-H** [comment]
Does running `composer update` followed by `php _build/transport.core.php` and then going through the installer work for you?

**Comment by Mark-H** [comment]
I also wonder if _build/data/transport.core.system_settings.php may have a typo on line 1752 but cant load that file on mobile because it's too big.

**Comment by Ibochkarev** [comment]
> Does running `composer update` followed by `php _build/transport.core.php` and then going through the installer work for you?

I will give all the information within an hour

**Comment by Ibochkarev** [comment]
> I also wonder if _build/data/transport.core.system_settings.php may have a typo on line 1752 but cant load that file on mobile because it's too big.

https://github.com/modxcms/revolution/blob/3.x/_build/data/transport.core.system_settings.php#L1751-L1759

**Comment by Mark-H** [comment]
https://github.com/modxcms/revolution/commit/d463e3fe5d8f8bd7c6c88b5b6db1f2b1439da425#diff-c2c883d027cc489d562c37b3396282d01feda1108ebdb3501eff755b34e263b7R1751

'modSystemSetting' should be modSystemSetting::class on line 1751

**Comment by Ibochkarev** [comment]
> [d463e3f#diff-c2c883d027cc489d562c37b3396282d01feda1108ebdb3501eff755b34e263b7R1751](https://github.com/modxcms/revolution/commit/d463e3fe5d8f8bd7c6c88b5b6db1f2b1439da425#diff-c2c883d027cc489d562c37b3396282d01feda1108ebdb3501eff755b34e263b7R1751)
> 
> 'modSystemSetting' should be modSystemSetting::class on line 1751

I will fix it now
