### ISSUE TITLE
MODX 3.0 javascript error during installation

### ISSUE THREAD

**Issue by DenCrazy** [modxcms/revolution#16133]
When installing at the stage of specifying access to the connector.php database, nothing responds. This is causing an error in the console:
`Uncaught SyntaxError: Unexpected token ')'
    at Object.Ext.util.JSON.decode (ext-core.js:9:80563)
    at HTMLAnchorElement.success (database.js:22:21)
    at Ext.data.Connection.b (ext-core.js:9:75506)
    at e (ext-core.js:9:13506)
    at ext-core.js:9:14107
Ext.util.JSON.decode @ ext-core.js:9
success @ database.js:22
b @ ext-core.js:9
e @ ext-core.js:9
(anonymous) @ ext-core.js:9
setInterval (async)
n @ ext-core.js:9
j @ ext-core.js:9
request @ ext-core.js:9
request @ ext-core.js:9
testConnection @ database.js:19
z @ ext-core.js:9`

PHP Version 7.4
If you need more information, I will provide.

**Comment by rthrash** [comment]
Is this a new install, or an upgrade? What other versions of the stack are you running (DB, web server, server OS)?

**Comment by DenCrazy** [comment]
This is a new installation. Server Configuration:

- Сent OS 7
- DB MySQL 8.0
- WEB Apache
- PHP Version 7.4.19

MODX version 2.8.3 was installed on this server configuration without any problems.

**Comment by DenCrazy** [comment]
> This is a new installation. Server Configuration:
> 
> * Сent OS 7
> * DB MySQL 8.0
> * WEB Apache
> * PHP Version 7.4.19
> 
> MODX version 2.8.3 was installed on this server configuration without any problems.

This is a new installation. Server Configuration:

Сent OS 7
DB MySQL 8.0
WEB Apache
PHP Version 7.4.19
MODX version 2.8.3 was installed on this server configuration without any problems.

**Comment by DenCrazy** [comment]
> Is this a new install, or an upgrade? What other versions of the stack are you running (DB, web server, server OS)?

This is a new installation. Server Configuration:

Сent OS 7
DB MySQL 8.0
WEB Apache 2.4
PHP Version 7.4.19
MODX version 2.8.3 was installed on this server configuration without any problems.

**Comment by Jako** [comment]
Please look in the PHP error log and/or in the connector response content. The error has to be visible there.

**Comment by JoshuaLuckers** [comment]
@DenCrazy can you provide the info requested bij Jako? Thanks a lot.

**Comment by danieldelagarzaponce** [comment]
I got this error in the installation -> probably related to the hosting i think is godaddy

VM2106:1 Uncaught SyntaxError: Unexpected token ')'
    at doDecode (ext-core.js:3:15806)
    at Object.decode (ext-core.js:3:17299)
    at HTMLAnchorElement.success (database.js:22:21)
    at Ext.data.Connection.handleResponse (ext-core.js:3:13897)
    at a (ext-core.js:1:14105)
    at ext-core.js:1:14681

**Comment by Mark-H** [comment]
Check the response of the ajax request that gets sent when submitting connection details. It looks like that does not have a valid response.

**Comment by prapdm** [comment]
I have the same bug.
connector.php response:

<br />
<b>Fatal error</b>:  Cannot declare class xPDO\Om\xPDODriver, because the name is already in use in <b>/home/XXX/domains/hxx.xxxx.pl/public_html/core/vendor/xpdo/xpdo/src/xPDO/Om/xPDODriver.php</b> on line <b>25</b><br />

**Comment by Mark-H** [comment]
Does your `core/config/config.inc.php` have a `$database_type` specified or was that replaced with `{database_type`}? Should be on line 5. 

If it has the thingy with braces, restore your config file from backup, and restart the setup at the beginning by going to `/setup/`.

**Comment by prapdm** [comment]
Yes, I restored old config.inc.php from 2.7.3, and start working. Thx.

**Comment by smg6511** [comment]
Stale issue, likely wasn't a bug (at least not a reproducible one with the given information).
